# Generated by Django 5.2.5 on 2025-08-09 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_tipo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Despesa',
            new_name='Transacao',
        ),
    ]
